### PR TITLE
Add import names for external deps in modules

### PR DESCRIPTION
**Pull request by knuton**
We implemented external dependencies in modules to be only a list of
identifiers. In this case, the name under which a library is imported
in a module is the same as the name of the dependency that is announced
to the outside world.

But we may not want the two to collapse in all cases. With regular
Spaghetti modules, we ONLY need the module (package) identifier, as
modules are compiled so that in the host language each module may
import any other module under whatever name it desires.

Because for external dependencies we don't generate any proxies that can
be imported by language-native means, we are doing both package
provisioning (for this we need a package identifier), as well as an
automatic import (for this we need a variable identifier). It is
impractical if those two are forced to be the same.

### CODE REVIEW

**Comment by lptr** [comment]
IIRC, we've talked about doing this already. One thing I think would be nice to allow users to do (both in the Gradle plugin and the command-line tool) is to specify just a single `name` (instead of a `name:mapping` pair), which would automatically map to `name:name`.

I've also thought about keeping compatibility with existing Spaghetti modules, i.e. the ones that have `External-Dependencies` in the `name` format (as opposed to the `name:mapping` format). Not sure if this is worth it, though.

**Comment by knuton** [comment]
Hm, that's a good point. Creating a unified reader it should be relatively straightforward to achieve this for all three cases. I'll look into it.

**Comment by knuton** [comment]
Added support for "legacy" notation.

**Comment by knuton** [comment]
I introduced some weird bug. Checking.

**Pull request merged**
